FROM mcr.microsoft.com/dotnet/sdk:8.0-azurelinux3.0 AS build
WORKDIR /app

COPY ./ ./
RUN dotnet publish Presentation-Kattencafe -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0-azurelinux3.0-distroless-extra
WORKDIR /app
COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "Main.dll"]