/// <reference types="Cypress" />
describe('CrudMenuItem', () => {
  it('Create MenuItem', () => {
    cy.visit('http://admin.localhost/')
    cy.get(".UsernameInput").type("Admin")
    cy.get(".UsernameInput").should("have.value", "Admin")
    cy.get(".PasswordInput").type("TL1")
    cy.get(".PasswordInput").should("have.value", "TL1")
    cy.get(".LoginSubmit").click()
    cy.get(".LoginToaster").first().contains("Succes:")
    cy.get(".MenuButton").click()
    cy.get(".NieuwMenuItem").click()
    cy.get(".MenuitemName").type("CypressK")
    cy.get(".MenuitemName").should("have.value", "CypressK")
    cy.get(".MenuItemDesciption").type("Cypresstest")
    cy.get(".MenuItemDesciption").should("have.value", "Cypresstest")
    cy.get(".MenuItemPrice").type("2")
    cy.get(".MenuItemPrice").should("have.value", "2")
    cy.get(".send-button").click()
  })

  it('Delete MenuItem', () => {
    cy.visit('http://admin.localhost/')
    cy.get(".UsernameInput").type("Admin")
    cy.get(".UsernameInput").should("have.value", "Admin")
    cy.get(".PasswordInput").type("TL1")
    cy.get(".PasswordInput").should("have.value", "TL1")
    cy.get(".LoginSubmit").click()
    cy.get(".LoginToaster").first().contains("Succes:")
    cy.get(".MenuButton").click()
    cy.get(".MenuCard").contains("CypressK").get(".DeleteItemButton").last().click()
    cy.get(".DeleteConfirm").click()
    cy.get(".MenuCard").contains("CypressK").should("not.exist")
  })
})