/// <reference types="Cypress" />
describe('CrudCAT', () => {
  it('Create Kat', () => {
    cy.visit('http://admin.localhost/')
    cy.get(".UsernameInput").type("Admin")
    cy.get(".UsernameInput").should("have.value", "Admin")
    cy.get(".PasswordInput").type("TL1")
    cy.get(".PasswordInput").should("have.value", "TL1")
    cy.get(".LoginSubmit").click()
    cy.get(".LoginToaster").first().contains("Succes:")
    cy.get(".KatButton").click()
    cy.get(".NieuwKatButton").click()
    cy.get(".CatnameInput").type("CypressKat")
    cy.get(".CatnameInput").should("have.value", "CypressKat")
    cy.get(".CatdescriptionInput").type("Cypresstestcat")
    cy.get(".CatdescriptionInput").should("have.value", "Cypresstestcat")
    cy.get(".KatCreateButton").click()
  })

  it('Delete Kat', () => {
    cy.visit('http://admin.localhost/')
    cy.get(".UsernameInput").type("Admin")
    cy.get(".UsernameInput").should("have.value", "Admin")
    cy.get(".PasswordInput").type("TL1")
    cy.get(".PasswordInput").should("have.value", "TL1")
    cy.get(".LoginSubmit").click()
    cy.get(".LoginToaster").first().contains("Succes:")
    cy.get(".KatButton").click()
    cy.get(".CatCard").contains("CypressKat").get(".DeleteCatButton").last().click()
    cy.get(".DeleteConfirm").click()
    cy.get(".CatCard").contains("CypressKat").should("not.exist")
  })
})