describe('Crud', () => {
  it('Create Kat', () => {
    cy.visit('https://admin.localhost/')
    cy.get(".UsernameInput").type("Admin")
    cy.get(".UsernameInput").should("have.value", "Admin")
    cy.get(".PasswordInput").type("TL1")
    cy.get(".PasswordInput").should("have.value", "TL1")
    cy.get(".LoginSubmit").click()
    cy.get(".LoginToaster").first().contains("Succes:")
    cy.get(".KatButton").click()
    cy.get(".NieuwKatButton").click()
    cy.get(".CatnameInput").type("CypressKat")
    cy.get(".CatnameInput").should("have.value", "CypressKat")
    cy.get(".CatdescriptionInput").type("Cypresstestcat")
    cy.get(".CatdescriptionInput").should("have.value", "Cypresstestcat")
    cy.get(".KatCreateButton").click()
  })

  it('Delete Kat', () => {
    cy.visit('https://admin.localhost/')
    cy.get(".UsernameInput").type("Admin")
    cy.get(".UsernameInput").should("have.value", "Admin")
    cy.get(".PasswordInput").type("TL1")
    cy.get(".PasswordInput").should("have.value", "TL1")
    cy.get(".LoginSubmit").click()
    cy.get(".LoginToaster").first().contains("Succes:")
    cy.get(".KatButton").click()
    cy.get(".DeleteCat").last().click()
    cy.get(".DeleteConfirm").click()
  })
})