name: Automated API tests using Postman CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ PMAK-6752c17c17ac300001926a29-70c02a0d275900da13deb9234598e27bb8 }}
      - name: Run API tests
        run: |
          postman collection run "40250504-debcd5ce-06e2-4fb3-a1f0-9f87c3169c91"
