name: CodeQualityAnalsis
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    CQA:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install -r 
              
            - name: Install Eslint Admin
              run: cd Frontend-Admin && npm init @eslint/config@latest

            - name: Install Eslint Klant
              run: cd Frontend-Klant && npm init @eslint/config@latest

            - name: Run Code quality lint tests for Admin
              run: cd Frontend-Admin && pnpm npx eslint

            - name: Run Code quality lint tests for Klant
              run: cd Frontend-Klant && pnpm npx eslint
